### PR TITLE
Fix issue where youtube resets speed when fullscreen

### LINKED ISSUE #370: Youtube speed resets every time while toggling Full Screen and back.
Apparently, this speed-reset issue has been happening when toggling the theater mode but now this issue has recently started to happen when opening the Full Screen, as well as going back to the normal screen from the Full Screen. I go on Full Screen and back often which is why this has created some annoyance for me and I am sure I am not the only one getting annoyed by this.

Also, hopefully, this info will be helpful when it comes to fixing this issue:

 I believe this issue has started to happen after youtube added this **"Scroll for details"** function on Full-Screen videos where you get to scroll down and see the comments/related videos even on Full-Screen mode.

scroll for details

I guess I can get used to this but it would've been amazing to see this problem get fixed, hopefully, it has an easy fix. Btw, I am using Chrome on a Macbook Pro and didn't test the issue on other browsers/systems but I assume they would have the same outcome due to Youtube's recent change on Full-Screen mode. I should also say that **Video Speed Controller** is my most favorite browser extension ever and I am so grateful to its creator, saved me so much time!

### PR DESCRIPTION
**Pull request by jacobcolbert**
Fixes #370

Track the speed of a video based on its source at time of last
ratechange. Newly initialize video controller with same speed as
other controllers of video with same source automatically.

Allow different speeds for different sources in same frame. Make a
controller button press only affect that controller.

Remove the deprecated settings.

### CODE REVIEW

**Comment by alystair** [comment]
I have a feeling the original creator has stopped working on the extension, has never responded to people on GitHub - maybe worth while creating a new extension?

**Comment by jacobcolbert** [comment]
I don't think that is true, he pushed out a release a month or so ago. Probably busy with some other important things though from the looks of his profile. But I def recommend downloading my version and running it while we wait because the problem drove me up the wall!

I just noticed that @canarslan12 has a pull request to fix this too using a different method. Might help if we can reach a consensus ourselves about it. I prefer my approach as it solves two birds with one stone (allows different speeds on different videos on same page). It also moves us in the direction of src based controllers that will stop double controllers on empty video containers. Do you see any problems with my solution?

File: inject.js [hunk 1]
```diff
@@ -142,14 +127,14 @@
         if (event.target.readyState > 0) {
           var speed = this.getSpeed();
           this.speedIndicator.textContent = speed;
-          tc.settings.speed = speed;
```
Comment (igrigorik) [inline inject.js]: Wouldn't this create an implicit history of every video you watch, and grow in an unbounded manner? The former is a non starter from a user privacy perspective.

File: inject.js [hunk 2]
```diff
@@ -393,11 +378,17 @@
   function runAction(action, document, value, e) {
     var videoTags = document.getElementsByTagName('video');
     videoTags.forEach = Array.prototype.forEach;
-
+	if (e){
```
Comment (igrigorik) [inline inject.js]: Can you elaborate on what this logic is doing?

File: inject.js (hunk 1 above)
Comment (jacobcolbert) [reply inject.js]: The Map containing the speeds for each video sources is never saved anywhere, and would disappear whenever the user loads a new site or closes the tab.

The variable tc.settings.speed is just the latest speed and is stored for people who have "remember speed" checked.

File: inject.js (hunk 2 above)
Comment (jacobcolbert) [reply inject.js]: When the controller buttons are pressed it passes the event e to runAction. If runAction is called by a keyBinding than e is null and it will skip the following tests and change all video speeds.

We use the event to find the videoTag owning the controller. Rather than changing the speed of all videos we check each one to see if it has the same controller and only proceed if it does.

File: inject.js (hunk 1 above)
Comment (igrigorik) [reply inject.js]: 👍

File: inject.js (hunk 2 above)
Comment (igrigorik) [reply inject.js]: Can you please add a comment to capture this in the source as well?

File: inject.js [hunk 3]
```diff
@@ -127,13 +108,25 @@
...
       this.id = Math.random().toString(36).substr(2, 9);
       if (!tc.settings.rememberSpeed) {
-        tc.settings.speed = 1.0;
+		if (!tc.settings.speeds[target.src]) {
+			tc.settings.speeds[target.src] = 1.0;
+		}
         setKeyBindings("reset", getKeyBindings("fast")); // resetSpeed = fastSpeed
-      }
+      } else{
+		  tc.settings.speeds[target.src]=tc.settings.speed;
```
Comment (igrigorik) [inline inject.js]: formatting: add spaces around `=`.

**Comment by jacobcolbert** [comment]
Think that should all be better. Did not realize notepad++ was using tabs. Need to look into that...

**Comment by garyking** [comment]
I can't wait for this update! Any ETA for the next release?
